### ISSUE TITLE
Debbuger still missing variables

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#78] opened 2016-07-15 14:27 UTC
<img width="1440" alt="screen shot 2016-07-14 at 7 56 20 pm" src="https://cloud.githubusercontent.com/assets/689092/16877555/000d3abe-4aa9-11e6-850c-3c128033c787.png">

**Comment by VISTALL** [comment] 2016-07-17 13:51
Hi. Sorry for delay, but it's not simple issue, i can't reproduce it without simple example

**Comment by winxalex** [comment] 2016-07-18 12:38
Don't how to create... What should I do. It is inside the Modal Dialog as you can see.???

**Comment by VISTALL** [comment] 2016-07-18 22:12
I saw. Try minimize code inside method. 

I have no problem with local var evaluation

![](http://klikr.org/9bae00baf934e7554713dbadbe0b.png)

**Comment by winxalex** [comment] 2016-07-18 22:17
It is in Modal Dialog might have been on other thread. its complex . See behaviourOrdInx is shown and logicCOmponentID not even not listed

**Comment by VISTALL** [comment] 2016-11-28 13:11
I close this issue. If you repeat it again. Create new with new description.

Thanks

**Closed as completed by VISTALL** 2016-11-28 13:11 UTC
Labels: prio: normal, type: bug
