### ISSUE TITLE
Add support for builtin packages from UnityEditor

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-unity3d#164] opened 2018-12-06 05:02 UTC
From path
```
S:\Unity\Unity 2018.2.8f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.xr
```

**Comment by airzocker** [comment] 2019-04-07 15:51
hello,
is there any solution yet to fix consulo's problem with not resolving Unity's now built-in (automatically installed from package manager) TextMesh Pro?
because it shows me errors on all of it...

Thanks

**Comment by VISTALL** [comment] 2019-04-08 05:08
Hello @airzocker. Can you say your Unity version? When i tested this issue not provide any problem (due it contains only Unity deps).

**Comment by airzocker** [comment] 2019-04-08 15:56
@VISTALL My unity version is 2018.3.2f1 and my consulo version is about half a year old (i'll update it if it's fixed in newer version). The Problem is that with the newer unity versions, TextMesh Pro is automatically installed but from the package manager, so the scripts it contains are not in the assets (and i don't even think in the project) folder and because of that consulo doesn't resolve (recognise) the TextMesh Pro usages in my scripts.

Thanks for you help

**Comment by VISTALL** [comment] 2019-04-08 16:04
Hello. Yeah, you have too old version. There was fixed many issues with package manager (like this https://github.com/consulo/consulo-unity3d/issues/167)

**Closed as completed** 2019-04-09 07:13 UTC
Labels: type: task, prio: normal
