### ISSUE TITLE
File moving may broke resolving

### ISSUE THREAD

**Issue by ernestp** [consulo/consulo-unity3d#29] opened 2015-07-26 08:39 UTC
For unknown reason code references sometime not resolved.
1. Import project
2. Open file Scripts/UsingBug.cs

This project compiles well in Unity 5.1.2 and MonoDevelop
Sample project https://www.dropbox.com/s/y5q3veuvca5sx5n/ConsuloSample28.zip?dl=0

**Comment by VISTALL** [comment] 2015-07-26 08:50
Strange. I imported and got this: 

![](http://klikr.org/6ad879a8827686f3d21719f3db12.png)

Try, first **ROOT_DIR** -> Right Click -> Sync Project

And then:
File -> Invalidate Caches

**Comment by ernestp** [comment] 2015-07-26 09:07
I've got that problem in this project by moving scripts to different folders.
Sync Project not help, but reimport does.
Invalidate caches also solve original problem, that was reason for creating this bug.
Seems that was some leftover from previous Consulo build.

**Comment by VISTALL** [comment] 2015-07-26 15:37
Can you say that file i need to move, for repeat problem?

**Comment by ernestp** [comment] 2015-07-26 16:20
I just reorganize files in Unity, trying to achieve same file structure as in my own project. Not sure if it was some concrete move. Just create new folder in Unity and drag and drop old files to new folder structure.

**Comment by ernestp** [comment] 2015-08-01 12:34
Updated Consulo and plugins. Some of classes is not resolved. Reimport, invalidate caches and synchronise files is not help.
![screenshot 2015-08-01 19 30 50](https://cloud.githubusercontent.com/assets/7553589/9021850/5919f756-3884-11e5-9cce-56c5714319db.png)

**Comment by VISTALL** [comment] 2015-08-01 20:37
Sorry for late answer. I cant reproduce:

![](http://klikr.org/22b7428259fbd8d39888ef8bd8e4.png)

**Comment by ernestp** [comment] 2015-08-08 06:46
Found some weird stuff regarding this bug. I has stable issue with GameSetting2 class, as on screen and clear caches reimport and synchronise was not help. But when I navigate to my project and delete .consulo folder prior reimport, then issue is gone. Seems that some leftovers in this folder is affecting reimport.

**Comment by VISTALL** [comment] 2015-12-27 13:16
I am closing this issue. If issue reproduced - need create new

**Closed as completed by VISTALL** 2015-12-27 13:17 UTC
Labels: prio: normal, type: bug

**Comment by Wambosa** [comment] 2016-07-28 02:32
first off, thank you for writing this amazing IDE!

confirmed that this issue still exists. I work on two machines. By renaming a folder on one machine and commit to source control, the other machine loses reference to the files in the new folder. The problem is most likely caused by me omitting the .consulo contents from source control.

The fix is to delete the .consulo folder and reimport.
This workaround is fine for me.

**Comment by VISTALL** [comment] 2016-07-28 02:36
You can use 'Re-import Project' (right click on project node)

**Comment by Wambosa** [comment] 2016-07-28 02:38
that is even easier. thank you :)
