### ISSUE TITLE
Unity Gutter Icon does not work on all classes

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo-unity3d#63] opened 2016-03-08 08:42 UTC
Clicking on this icon shows the error "Unity Editor is not opened" in some classes, while other are working fine. Unity is running simultaneously.

**Comment by VISTALL** [comment] 2016-03-08 08:54
UnityEditor is opened ? yes?

**Comment by sfjohansson** [comment] 2016-03-08 08:55
yes it is indeed...I'm on mac =O

**Comment by VISTALL** [comment] 2016-03-08 08:55
Strange

**Comment by sfjohansson** [comment] 2016-03-08 08:56
just tried also with the debug attach and that worked fine

**Comment by VISTALL** [comment] 2016-03-08 08:58
This library is exists in project ? https://github.com/consulo/UnityEditorConsuloPlugin

**Comment by sfjohansson** [comment] 2016-03-08 08:58
getting this output in the system console:

```
2016-03-08 08:57:46,127 [47599042]   WARN - ditor.UnityEditorCommunication - Connect to localhost:58929 [localhost/127.0.0.1] failed: Connection refused 
org.apache.http.conn.HttpHostConnectException: Connect to localhost:58929 [localhost/127.0.0.1] failed: Connection refused
    at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:142)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
    at org.mustbe.consulo.unity3d.editor.UnityEditorCommunication.request(UnityEditorCommunication.java:81)
    at org.mustbe.consulo.unity3d.editor.UnitySceneFile.navigate(UnitySceneFile.java:32)
    at com.intellij.codeInsight.daemon.impl.PsiElementListNavigator$1.consume(PsiElementListNavigator.java:86)
    at com.intellij.codeInsight.daemon.impl.PsiElementListNavigator$1.consume(PsiElementListNavigator.java:80)
    at com.intellij.codeInsight.daemon.impl.PsiElementListNavigator.navigateOrCreatePopup(PsiElementListNavigator.java:101)
    at com.intellij.codeInsight.daemon.impl.PsiElementListNavigator.navigateOrCreatePopup(PsiElementListNavigator.java:80)
    at com.intellij.codeInsight.daemon.impl.PsiElementListNavigator.openTargets(PsiElementListNavigator.java:65)
    at com.intellij.codeInsight.daemon.impl.PsiElementListNavigator.openTargets(PsiElementListNavigator.java:56)
    at org.mustbe.consulo.unity3d.csharp.codeInsight.UnityCSharpLineMarkerProvider$2.navigate(UnityCSharpLineMarkerProvider.java:198)
    at com.intellij.codeInsight.daemon.NavigateAction.actionPerformed(NavigateAction.java:56)
    at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.performAction(EditorGutterComponentImpl.java:1611)
    at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:1574)
    at com.intellij.openapi.editor.impl.EditorImpl.processMouseReleased(EditorImpl.java:4323)
    at com.intellij.openapi.editor.impl.EditorImpl.access$12200(EditorImpl.java:125)
    at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter$2.run(EditorImpl.java:5877)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:5880)
    at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5761)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:273)
    at java.awt.Component.processMouseEvent(Component.java:6414)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6179)
    at java.awt.Container.processEvent(Container.java:2084)
    at java.awt.Component.dispatchEventImpl(Component.java:4776)
    at java.awt.Container.dispatchEventImpl(Container.java:2142)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
    at java.awt.Container.dispatchEventImpl(Container.java:2128)
    at java.awt.Window.dispatchEventImpl(Window.java:2492)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:690)
    at java.awt.EventQueue$3.run(EventQueue.java:688)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:640)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:382)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:241)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:228)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:431)
    at java.net.Socket.connect(Socket.java:527)
    at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
    at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
    ... 64 more
```

**Comment by sfjohansson** [comment] 2016-03-08 09:00
Yes it does, let me just update it... I'm using unity 4.7.1

**Comment by VISTALL** [comment] 2016-03-08 09:06
Looks like UnityEditor plugin didnot bind api server. I will check with 4.7 Unity - maybe today

**Comment by sfjohansson** [comment] 2016-03-08 09:10
This seems to apply to some newer classes.. I tried reimporting that project, with the same result..so the reason it works on older classes might be due to cached data. Whereafter it has broken, as that could also explain the bug where not all scenes where listed.

**Comment by VISTALL** [comment] 2016-03-08 09:12
I think its Unity problem. Unity have refresh queue - and it fully **unload plugin** and then **load**. Plugin is project wide, and its a problem

**Comment by sfjohansson** [comment] 2016-03-08 10:32
I've tried the latest unity plugin, the only difference now is that nothing happens...i e no showing the "not open popup", it still works on the older classes as usual.  The classes that are not working, are never but not like five minutes ago, they still have some history..so maybe this is actually broken after 4.6

**Comment by VISTALL** [comment] 2016-03-08 15:41
Cant reproduce :(

**Comment by sfjohansson** [comment] 2016-03-09 14:22
I'll put together a package if I can isolate the edge case when it breaks :)

**Comment by sfjohansson** [comment] 2016-03-10 08:41
On side note while messing with this..It could be quite useful to in addition to scenes..also get a list of prefabs that uses a component/class

**Comment by VISTALL** [comment] 2016-03-10 08:42
Yeah. But i idk how show it in this file

**Comment by sfjohansson** [comment] 2016-03-10 08:48
hmm maybe just have that one list and then use an icon to show if it is scene file or a prefab

**Comment by VISTALL** [comment] 2016-03-10 09:00
ref https://github.com/consulo/consulo-unity3d/issues/64

**Comment by sfjohansson** [comment] 2016-03-10 09:10
Cool.. :) when I'm at it...shamelessly adding feature creep... if it is possible find scenes and prefabs...then it's probably possible to actually get all assignments for a certain variable in a class across the project..so for each monobehaviour and it's public variables..the data should be extractable from the scene files or prefab files..

**Comment by VISTALL** [comment] 2016-03-10 09:12
I already thinking about this feature. But - i dont time for write analyzer scene file(for search variables and correct classes)

**Comment by sfjohansson** [comment] 2016-03-10 09:19
I can imagine...there are a lot of clever things that can be done but it's important to choose...just got the idea looking at prefab definition file and it looked like it could be done by doing a search matching m_attributeXXX and script file ID

**Comment by VISTALL** [comment] 2016-03-10 10:02
Oh. Class can be attached to **.prefab**. I did not know that

**Comment by sfjohansson** [comment] 2016-03-10 10:09
Yeah..I believe they are all YAML..without digging into it as an expert.. So I'd be tempted to say that prefab and scene files are pretty much same thing..but the other one contains more stuff...and a few extra bits of data.

**Comment by VISTALL** [comment] 2016-03-10 10:11
Yeah, its YAML files. I am already added support for **prefab** marker for C# files

**Comment by sfjohansson** [comment] 2016-03-10 10:13
Just like that... awesome... :)

**Comment by VISTALL** [comment] 2016-03-10 10:45
Bad but - https://github.com/consulo/consulo-unity3d/issues/64 i closed. I did not found a way.

**Comment by VISTALL** [comment] 2016-04-02 19:07
I close this issue. If it repeated, and reproduced - need create new :)

**Closed as completed by VISTALL** 2016-04-02 19:07 UTC
Labels: prio: normal, type: bug
