### ISSUE TITLE
Cannot debug Coroutines

### ISSUE THREAD

**Issue by jmadaminov** [consulo/consulo-unity3d#91] opened 2016-11-18 06:08 UTC
Hi, I have problems debugging inside coroutines. Debugger simply doesn't run inside IEnumerator Coroutine. I've tried visual studio and monodevelop they both work. But Consulo doesn't.

**Comment by VISTALL** [comment] 2016-11-18 09:51
Hi. Can you attach simple project? And what Unity used?

**Comment by jmadaminov** [comment] 2016-11-18 18:37
Hi, thanx for your fast reply. I used 5.4.2 unity version. But before that
i tried on previous versions also months ago, did not work either. Sorry
this time i cannot send the project but the debugger doesn't work inside
any coroutine. I mean i set a breakpoint and the debugger never reaches it
while the code runs perfectly. Its the only reason i do not use Consulo all
the time. Can u tell me, if it works for you, can you debug inside
coroutines? If yes can you tell me if you have any plugins?
Best regards.

On Nov 18, 2016 14:52, "Valeriy Semenchuk" notifications@github.com wrote:

Hi. Can you attach simple project? And what Unity used?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/consulo/consulo-unity3d/issues/91#issuecomment-261491533,
or mute the thread

**Comment by VISTALL** [comment] 2016-11-18 18:39
I am not Unity user. I need some example for it. Looks like you found a bug. Without example i can't fix it.

Thanks

**Comment by jmadaminov** [comment] 2016-11-18 18:49
Here is a simple class with a coroutine

using UnityEngine;
using System.Collections;

public class MyClass : MonoBehaviour {

void Start (){
//Debugger works fine

StartCoroutine(MyCoroutine());

}

IEnumerator MyCoroutine () {

//Debugger not working

string check = "checking"
Debug.Log(check);

yield return null;

}

}

**Comment by VISTALL** [comment] 2016-11-18 18:54
Oh. Yield. It's compiler "sugar" (need specific handle on debugger side) - looks like some logic i missed.

Thanks for example. Currenly i don't have access to my home PC(outside my home for one month) - i will try fix this issue on my notebook(but not think that i can fix it).

Can you say Consulo version ?(and Unity plugin version, you can find it in preferences/settings)

Thanks

**Comment by jmadaminov** [comment] 2016-11-18 19:07
Consulo version is #1401
Unity3D plugin version is #2703 (updated 11/19/2016

what do you mean by "(but not think that i can fix it)" do you mean the problem may not be fixed at all or you just cannot fix it at the current time? 
When are you planning to release 2.0?

**Comment by VISTALL** [comment] 2016-11-18 19:15
Current time

My notebook have bad hdd (and i have bad internet connection). It will be a problem for me download all required soft for me (unity, etc).

I am preparing Consulo 2 for open(its opened already, but i not publish download links) - but my "unexpected vacation" broke all.

Just need wait :(

Sorry

**Comment by jmadaminov** [comment] 2016-11-18 19:21
Ok i will wait, can you please comment here once you fix the issue. Thanx a lot, keep up the good work!)

**Comment by VISTALL** [comment] 2016-11-20 12:36
Tested on Unity 5.5. Will try after downloading 5.4.2

![](http://klikr.org/e98d99c1a3e25d206ca0290f5159.png)

**Comment by jmadaminov** [comment] 2016-11-20 12:40
Did u fix anyting or is it working by itself? Which consulo are you using?

**Comment by VISTALL** [comment] 2016-11-20 12:42
It's Consulo 2. There no changes in debug between Consulo 1 & Consulo 2. 

I will downgrade - and check (due Unity 5.5 have new Mono compiler)

**Comment by VISTALL** [comment] 2016-11-20 13:04
I had Unity 5.1 on my notebook. It works too. Looks like is not simple problem. Waiting Unity 5.4.2

**Comment by jmadaminov** [comment] 2016-11-20 13:09
Do u use any editor plugin?

**Comment by VISTALL** [comment] 2016-11-20 13:11
Nope. Debug works without any UnityEditor plugins. 

Almost
![](http://klikr.org/86809f988b2e9b06a5e56fe78d92.png)

**Comment by VISTALL** [comment] 2016-11-20 13:27
And. Can't reproduce ;(

![](http://klikr.org/5e4133009e278f5ba01793a1702c.png)

You can download Consulo2 (https://ci.consulo.io/job/consulo/). But i am sure - it will not helps.

**Comment by jmadaminov** [comment] 2016-11-20 13:34
Strange...will try with consulo 2 thanx a lot

**Comment by VISTALL** [comment] 2016-11-20 13:36
Can you create simple project - with simple class, and try to debug it? If debugger failed (give me Assembly-CSharp.dll from project).  I will check your bytecode.

**Comment by jmadaminov** [comment] 2016-11-20 13:45
I think i figured it out, the case occurs when u call another coroutine
from a coroutine. The first coroutine can be debugged but further
coroutine  is not, can you please try it

**Comment by VISTALL** [comment] 2016-11-20 13:54
Works
![](http://klikr.org/25e1d896ebdf10ddd12937d00ec4.png)

**Comment by jmadaminov** [comment] 2016-11-20 14:09
![untitled](https://cloud.githubusercontent.com/assets/12813066/20463441/aa496722-af54-11e6-88ca-0663b6bf3efe.png)

here is my project, reaching the *Debug.Log("Checking"); but breakpoint is not reached....

**Comment by VISTALL** [comment] 2016-11-20 14:11
yeah. Looks like debugger lines is not resolved inside yield block. Hm

**Comment by VISTALL** [comment] 2016-11-20 14:16
https://github.com/VISTALL/unity-2d-pong-game

Can you clone this game - and try debug **Ball.cs:16**?

**Comment by jmadaminov** [comment] 2016-11-20 14:16
ok

**Comment by jmadaminov** [comment] 2016-11-20 14:26
![image](https://cloud.githubusercontent.com/assets/12813066/20463520/cbd690a2-af56-11e6-993c-b5013a884e94.png)

Tried it and it's working and it gave me the following IDE error

Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:751)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:699)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:682)
    at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:346)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:327)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:316)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:80)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:99)
    at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:305)
    at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:295)
    at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java:38)
    at org.mustbe.consulo.unity3d.unityscript.lang.impl.UnityScriptPsiSearcher.findTypesImpl(UnityScriptPsiSearcher.java:49)
    at org.mustbe.consulo.dotnet.lang.psi.impl.DotNetNamespaceCacheManager.computeTypesImpl(DotNetNamespaceCacheManager.java:335)
    at org.mustbe.consulo.dotnet.lang.psi.impl.DotNetNamespaceCacheManager.computeTypes(DotNetNamespaceCacheManager.java:317)
    at org.mustbe.consulo.dotnet.resolve.impl.DotNetPsiSearcherImpl.findTypesImpl(DotNetPsiSearcherImpl.java:62)
    at org.mustbe.consulo.dotnet.resolve.DotNetPsiSearcher.findTypes(DotNetPsiSearcher.java:82)
    at org.mustbe.consulo.dotnet.resolve.DotNetPsiSearcher.findType(DotNetPsiSearcher.java:112)
    at org.mustbe.consulo.dotnet.resolve.DotNetPsiSearcher.findType(DotNetPsiSearcher.java:105)
    at consulo.dotnet.debugger.DotNetStackFrame$2.compute(DotNetStackFrame.java:152)
    at consulo.dotnet.debugger.DotNetStackFrame$2.compute(DotNetStackFrame.java:148)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:905)
    at consulo.dotnet.debugger.DotNetStackFrame.getSourcePosition(DotNetStackFrame.java:147)
    at com.intellij.xdebugger.impl.frame.XDebuggerFramesList$XDebuggerFrameListRenderer.customizeCellRenderer(XDebuggerFramesList.java:149)
    at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:58)
    at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:34)
    at javax.swing.plaf.basic.BasicListUI.paintCell(BasicListUI.java:209)
    at javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:317)
    at javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:240)
    at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
    at javax.swing.JComponent.paintComponent(JComponent.java:780)
    at com.intellij.ui.components.JBList.paintComponent(JBList.java:143)
    at javax.swing.JComponent.paint(JComponent.java:1056)
    at com.intellij.ui.components.JBList.paint(JBList.java:97)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JViewport.paint(JViewport.java:728)
    at com.intellij.ui.components.JBViewport.paint(JBViewport.java:119)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at com.intellij.ui.tabs.impl.JBTabsImpl.paintChildren(JBTabsImpl.java:2268)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at com.intellij.ui.tabs.impl.JBTabsImpl.paint(JBTabsImpl.java:2263)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at com.intellij.ui.tabs.impl.JBTabsImpl.paintChildren(JBTabsImpl.java:2268)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at com.intellij.ui.tabs.impl.JBTabsImpl.paint(JBTabsImpl.java:2263)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at com.intellij.openapi.wm.impl.ToolWindowsPane.paintChildren(ToolWindowsPane.java:192)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
    at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
    at javax.swing.JComponent.paint(JComponent.java:1042)
    at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
    at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
    at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
    at java.awt.Container.paint(Container.java:1975)
    at java.awt.Window.paint(Window.java:3904)
    at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.java:515)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
    at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
    at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:892)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:406)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

---

Indexing started at:
java.lang.Throwable
    at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:165)
    at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.queueTasks(PushedFilePropertiesUpdaterImpl.java:203)
    at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.processAfterVfsChanges(PushedFilePropertiesUpdaterImpl.java:129)
    at com.intellij.psi.impl.file.impl.PsiVFSListener$1.after(PsiVFSListener.java:83)
    at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:285)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
    at com.sun.proxy.$Proxy20.fileWithNoDocumentChanged(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:140)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:90)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:118)
    at com.sun.proxy.$Proxy20.fileWithNoDocumentChanged(Unknown Source)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.contentsChanged(FileDocumentManagerImpl.java:605)
    at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
    at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
    at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
    at com.sun.proxy.$Proxy15.contentsChanged(Unknown Source)
    at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
    at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
    at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:287)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
    at com.sun.proxy.$Proxy16.after(Unknown Source)
    at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:791)
    at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEventsInWriteAction(RefreshSessionImpl.java:230)
    at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:210)
    at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$1$1$1.run(RefreshQueueImpl.java:92)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
    at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$1$1.run(RefreshQueueImpl.java:89)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:892)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:406)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by VISTALL** [comment] 2016-11-20 14:33
I will fix exception. But. Looks like need better example for reproduce :(

**Comment by jmadaminov** [comment] 2016-11-20 14:36
i will try to find the reason its happening in my project and inform you if i'll find it, Thanx for your time

**Comment by VISTALL** [comment] 2016-11-20 14:41
Can you download http://ilspy.net/

Then open Assembly-CSharp.dll. Select IL language (at toolbar menu). And  show me nested class names ?

Pattern is "<([\S\d]+)>c__Iterator([\d]+)". I think i missed something

**Comment by VISTALL** [comment] 2016-11-20 14:48
Like this
![](http://klikr.org/b64f0eadac56a8dc6c1eed4928d5.png)

**Closed as completed** 2016-11-20 18:56 UTC
Labels: prio: normal, type: bug

**Comment by jmadaminov** [comment] 2016-11-21 13:54
new update fixed the bug. Thanx a lot!
