### ISSUE TITLE
Access is denied on Project Import

### ISSUE THREAD

**Issue by supalaplic** [consulo/consulo-unity3d#47] opened 2015-12-04 14:18 UTC
I get this error when I try to import an Unity project (as provided in tutorial video). I did the same steps on a different computer and it worked.

 <code>RuntimeException: java.io.FileNotFoundException: F:\Server\Match 3 ios\Match3Game (Access is denied): java.io.FileNotFoundException: F:\Server\Match 3 ios\Match3Game (Access is denied)</code>

Stack:
<code>
java.lang.RuntimeException: java.io.FileNotFoundException: F:\Server\Match 3 ios\Match3Game (Access is denied)
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at org.mustbe.consulo.visualStudio.util.VisualStudioSolutionParser.parse(VisualStudioSolutionParser.java:74)
    at org.mustbe.consulo.visualStudio.importProvider.VisualStudioImportBuilder.loadItems(VisualStudioImportBuilder.java:297)
    at org.mustbe.consulo.visualStudio.importProvider.ui.VisualStudioSetupTargetStep.<init>(VisualStudioSetupTargetStep.java:53)
    at org.mustbe.consulo.visualStudio.importProvider.VisualStudioImporterProvider.createSteps(VisualStudioImporterProvider.java:49)
    at com.intellij.projectImport.ProjectImportProvider.addSteps(ProjectImportProvider.java:90)
    at com.intellij.ide.util.newProjectWizard.modes.ImportMode.createSteps(ImportMode.java:73)
    at com.intellij.ide.util.newProjectWizard.modes.WizardMode.getSteps(WizardMode.java:47)
    at com.intellij.ide.util.newProjectWizard.AddModuleWizard.initModuleWizard(AddModuleWizard.java:138)
    at com.intellij.ide.util.newProjectWizard.AddModuleWizard.<init>(AddModuleWizard.java:94)
    at com.intellij.ide.actions.ImportModuleAction.createImportWizard(ImportModuleAction.java:184)
    at com.intellij.ide.actions.ImportModuleAction.selectFileAndCreateWizard(ImportModuleAction.java:139)
    at com.intellij.ide.actions.ImportModuleAction.selectFileAndCreateWizard(ImportModuleAction.java:118)
    at com.intellij.ide.actions.ImportModuleAction.doImport(ImportModuleAction.java:64)
    at com.intellij.ide.actions.ImportModuleAction.actionPerformed(ImportModuleAction.java:60)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:248)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:263)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:233)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:106)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:532)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:640)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</code>

**Comment by VISTALL** [comment] 2015-12-04 14:19
Please use Import from **Unity Project Directory**(via Unity importer) not Visual Studio Importer

**Comment by VISTALL** [comment] 2015-12-05 16:00
Any news?

**Comment by supalaplic** [comment] 2015-12-07 08:04
Sorry for the late response but I don't work in weekends. Actually, I fixed it by opening my project in Visual Studios to generate the .sln file, then imported it to consulo, which seems to work fine for me.

**Comment by VISTALL** [comment] 2015-12-07 08:30
Its a bad idea. You will lose Debug feature (and some others).

Short example(before - drop **.consulo** dir in root project):

![](http://klikr.org/b58b859c09da018d0535653b77e1.gif)

**Comment by supalaplic** [comment] 2015-12-07 10:23
Well I tried importing it this way, but I get that error. Also I notice that my "Select File or Directory to import" looks a bit different. I succeeded on a different pc, but I have no idea why on mine it does not work
http://prntscr.com/9ban3m  

My stepts were: Close project -> Actions -> Import Project

**Comment by VISTALL** [comment] 2015-12-07 10:26
You dialog is valid. Next u need select **Unity3D**(you will see it, because you have many import providers), then you will see the same final dialog.

**Comment by supalaplic** [comment] 2015-12-07 10:43
Well, I might not get what I am supposed to do, but after I select my Unity dir (that is Match3Game from my screenshot), I press OK, then the window closes and nothing happens. If i open consulo in any other way, then I will get a notification with IDE internal error occurred and that error message.

**Comment by VISTALL** [comment] 2015-12-07 10:44
I think i am already fixed that exception (i catch it too), required Unity plugin update. Sry

**Comment by supalaplic** [comment] 2015-12-10 08:11
I did not receive any update :( 
Should I see it here : http://prntscr.com/9cfp1r  ?

**Comment by VISTALL** [comment] 2015-12-10 12:03
Right click on plugin list , and choose Reload. But i think you need update Consuli too. Last Consulo build is 1240

**Comment by supalaplic** [comment] 2015-12-10 13:26
I updated consulo and all the plugins, but the import still trows that error

**Comment by VISTALL** [comment] 2015-12-10 13:26
Please give me this error. Thanks (u need update C# & Unity3D plugins)

**Comment by supalaplic** [comment] 2015-12-10 14:17
Same error as above : 
<code>
15:04:56 RuntimeException: java.io.FileNotFoundException: F:\Server\Maction 3\Maction3 (Access is denied): java.io.FileNotFoundException: F:\Server\Maction 3\Maction3 (Access is denied)
</code>

I updated all plugins

**Comment by VISTALL** [comment] 2015-12-10 14:22
You used Visual Studio Importer, it not needed for Unity import. 

As i showed in my gif - i used Unity import (not VS)

**Comment by supalaplic** [comment] 2015-12-10 14:23
Well, I see no difference between what you do in your gif, and what I do :| ...

**Comment by VISTALL** [comment] 2015-12-10 14:24
For clear test - please remove Visual Studio Importer plugin, and try again

**Comment by supalaplic** [comment] 2015-12-10 14:27
Ok, I disabled Visual Studio Importer plugin and it works, but the thing is, I did the same steps as always, so it still confuse me how do I switch between different importers

**Comment by VISTALL** [comment] 2015-12-10 14:30
I thk at **Importer Choose Dialog** was select Visual Studio (it a bug - need reselect it)

**Comment by VISTALL** [comment] 2015-12-10 15:29
I will improve it. Thanks. I close this issue

**Comment by VISTALL** [comment] 2015-12-10 16:19
Looks like i reproduced this issue(no import provider select, Visual studio was selected as primary) and exception are throwed.

**Comment by VISTALL** [comment] 2015-12-10 17:26
It was platform issue. 

Fixed. 

Thanks.

**Closed as completed** 2015-12-10 17:26 UTC
Labels: prio: normal, type: bug
